### ISSUE TITLE
How to request a simulator as a webservice?

### ISSUE THREAD

**Issue by Dexter0015** [eureka2/G6K#1]
Hi,

I have successfully installed the project and import a simulator (as explained here: https://gitlab.com/pidila/sp-simulateurs-data/tree/master)

The simulator seems to works as entended, BUT, I would like to be able to request the simulator as a webservice.

So I try to look in the bundle config and find that there is a route defined for : /{simu}/api 

Unfortunatelly when I try to request the route I get an exception : 
"Error : API for this simulator is not implemented with code : 0"

When I start searching into the ApiController in order to figure out how I should process to configure an API for my simulator, but I'm a little lost.

Is it functionnal? Can you provide some help on that particular topic?

**Comment by eureka2** [comment]
hi,

Suppose your simulator is called "mysimulator" and has three steps:
Step 1: The user enters the data requested, then clicks on the "next" button
Step 2:  The user enters the data requested, then clicks on the "calculate" button
Step 3: Display of the simulation results

The following lines must be added to the "EUREKA\G6KBundle\Resources\ config\parameters.yml" file

```
     aPI:
         mysimulator:
             Step: 2
             Action: calculate
```

**Comment by Dexter0015** [comment]
Hi,
Thanks, much more clear now.
