### ISSUE TITLE
How to integrate the simulator on a webpage

### ISSUE THREAD

**Issue by Nulije** [eureka2/G6K#10]
Hi,

So everythinks works fine, i import the simulator "droit de succession", when i click on "try it", it works ang generate this url : http://localhost/simulateur/calcul/droits-succession/Demo/tryIt

My question could seems stupid (i'm sorry), but how can i insert this into a website ? How can i integrate the simulator in a php page ?

Best regards.

**Comment by eureka2** [comment]
G6K is a symfony application that produces its own pages.
To adapt these pages to your site, you need to create a view. To do this :
1. duplicate the directory "simulateur/src/EUREKA/G6KBundle/Resources/views/Demo" into a directory "simulateur/src/EUREKA/G6KBundle/Resources/views/mavue"
2. duplicate the directory "simulateur/src/EUREKA/G6KBundle/Resources/public/Demo" into a directory "simulateur/src/EUREKA/G6KBundle/Resources/public/mavue"
3. Change the default view of your simulators using the admin interface:
![image](https://user-images.githubusercontent.com/200478/45828821-d0c12e80-bcf9-11e8-8049-a70ca6b6755a.png)

4. You can access the simulator with: http://localhost/simulateur/calcul/droits-succession
5. Modify the TWIG templates in the "simulateur/src/EUREKA/G6KBundle/Resources/views/mavue" directory to suit your site.
6. Same for CSS style sheets in the "simulateur/src/EUREKA/G6KBundle/Resources/public/mavue" directory

N.B .: "mavue" can be replaced by a name at your convenience without spaces or special characters

**Comment by Nulije** [comment]
Did it and it works like a charm thanks, but is it possible to include the simulator with some php...

I've got a wordpress site and want to put the simulator in a wordpress page, so i won't be able to adapt the TWIG templates, and IFRAME is never a good solution....

Thx.

**Comment by eureka2** [comment]
Sorry, I do not know wordpress, I do not know how to integrate external pages.

**Comment by Nulije** [comment]
@opportus thanks for your response. I agree iframing the simulator is the simpliest solution et looks transparent for the users. But iframe in terms of SEO....

Like you said there's no many choice so Iframe with a shortcode seems to be the best solution.

Thx for the help.

**Comment by opportus** [comment]
@Nulije I didn't want my iframe content to be followed by crawlers as it would be considered as duplicate content...

**Comment by eureka2** [comment]
@Nulije,
opportus answered your question, I close this issue
