### ISSUE TITLE
Listboxes

### ISSUE THREAD

**Issue by richpeck** [eureka2/G6K#12]
Hi there,

I have an implementation of G6K running as an iFrame. Whilst the system works perfectly, there is an issue with the listbox component - because it's styled as an "absolute" position, it is not tracked in the DOM.

I have tried hacking the CSS and JS and feel the only way to do this reliably is to get rid of the JS listbox functionality. I want the default select box to appear again - how do you do this?

Many thanks

Rich

**Comment by eureka2** [comment]
Hi,

G6K is not designed to work in an iframe because the page expands (fields are added) as the simulation progresses.

Regarding your question, you can comment or delete lines 3286 to 3290 in the g6k.js script:
```
			$( ".disposition-classic select").each(function(k) {
				if (! this.hasAttribute('data-widget')) {
					$(this).listbox();
				}
			});
```

then reminify g6k.js in g6k.min.js

Best regards

**Comment by richpeck** [comment]
Thanks, yep appreciate the point about the iframe - got it working with this [iFrame resizer library](https://github.com/davidjbradshaw/iframe-resizer). As the listbox was not a DOM element, the resizer couldn't work correctly (as expected).

Your code worked (thank you). Do you have a donate button?
 
![iframe](https://user-images.githubusercontent.com/1104431/50041123-9d1b4980-0047-11e9-9a98-8d997d426b1d.gif)

**Comment by richpeck** [comment]
I can share the code for the resize if you wanted it for a wiki page or something.

**Comment by eureka2** [comment]
hi,

The listbox component is no longer used **by default** in the master, [3.x](https://github.com/eureka2/G6K/commit/9a9720a4671bf4677a6390d3f7a9608fecc3d8aa) and [4.x](https://github.com/eureka2/G6K/commit/9d22241c51933974c8c5d3c10a1dcc1a2d720481) branches

This component can be used explicitly on certain fields by simulator via the administration module, it is the responsibility of the administrator of the simulator.
