### ISSUE TITLE
G6K API for multisteps simulator

### ISSUE THREAD

**Issue by dridi93** [eureka2/G6K#15]
Hi,
I need to declare a web service for multisteps simulator,
How can i achive this !

Thanks

**Comment by eureka2** [comment]
Hi,

In a multi-step simulator, the last step provides the results of the simulation and the previous steps are used to acquire the data for the simulation. So the API must be declared to the last one. It is not possible for the moment to have results in intermediate stages.

**Comment by dridi93** [comment]
Hi, 
if i declare the API with the last step, how can i deal with other steps ?

**Comment by dridi93** [comment]
UP...

Any anwser please !

**Comment by eureka2** [comment]
Hi,

You must provide the data expected by the API (last step) as parameters of a GET request.

These data, either you get them with the other steps, or you get them with your own forms.

**Comment by dridi93** [comment]
Hi,
Who can i get data from previous steps, custom controller ?

**Comment by eureka2** [comment]
Can you explain exactly what you want to do?

**Comment by dridi93** [comment]
Okay,

If i declare the API at the last step, how can i get the previous steps data ?

**Comment by dridi93** [comment]
Hi,
Can i declare multi-api with diffrent names.

![image](https://user-images.githubusercontent.com/11330682/53010289-cb4d4900-343d-11e9-9f83-1a7b20fc8849.png)

**Comment by eureka2** [comment]
No, you can't !!

Please, explain what you want to do ? What's the final objective ?

**Comment by dridi93** [comment]
The final objective is to declare API for a simulator with multisteps

**Comment by dridi93** [comment]
no solutions !

**Comment by eureka2** [comment]
No, I do not have a solution because I do not understand what you want to do.

**Comment by dridi93** [comment]
Hi,
Sorry For Disturb, 

I installed the G6K simulator with a resource from [data.gouv.fr](https://www.data.gouv.fr/fr/datasets/simulateur-de-cout-du-certificat-dimmatriculation-carte-grise/) , now i need to setup the G6K API, I have declared it like this: `
    api:
        cout-certificat-immatriculation:
            step: 0
            action: calculer`
This simulator have multisteps form, my question is when i declared the API to the last step, how can i get informations from the other steps. 
![image](https://user-images.githubusercontent.com/11330682/53122684-7998e180-3557-11e9-851f-81d78ac98ae7.png)

**Comment by eureka2** [comment]
Hi,

You can not get informations from other steps.
If you declare an API, it means that your installation becomes a webservice accessible by **other** platforms. It is up to these platforms to acquire information **from their users** and then compose the access request to your webservice with these informations as parameters of the request.

**Comment by florientdelafoy** [comment]
> Hi,
> Sorry For Disturb,
> 
> I installed the G6K simulator with a resource from [data.gouv.fr](https://www.data.gouv.fr/fr/datasets/simulateur-de-cout-du-certificat-dimmatriculation-carte-grise/) , now i need to setup the G6K API, I have declared it like this: ` api: cout-certificat-immatriculation: step: 0 action: calculer`
> This simulator have multisteps form, my question is when i declared the API to the last step, how can i get informations from the other steps.
> ![image](https://user-images.githubusercontent.com/11330682/53122684-7998e180-3557-11e9-851f-81d78ac98ae7.png)

Did you find a solution ? I'm in the same situation as you
