### ISSUE TITLE
simulator and the registration card 

### ISSUE THREAD

**Issue by elodie66000** [eureka2/G6K#16]
Hello, my dear,

I want to know if we can test this simulator before we attempt installation.

My client would like to install a simulator with just a car plate information form and the registration card calculation is done automatically.

But I can’t find a visual of the result for this simulator.

Thank you so much.

**Comment by eureka2** [comment]
Hello,

I do not understand your question !

G6K is a tool for creating and publishing simulators, it is NOT a simulator.

If your question is about a particular simulator, you need to contact the producer of this simulator.

Best regards
