### ISSUE TITLE
Business rules

### ISSUE THREAD

**Issue by maxypayne** [eureka2/G6K#17]
Hello,
I have an issue with the business rules.
The taxeRegionaleY1 isn't divided by 2 for the vehicles more than 10 years.
Do I have to define something more than just import the json files?

Thank you in advance for your help,

**Comment by eureka2** [comment]
Hi,

I do not provide help for specific simulators that are not in this repository, you have to contact the simulator producer

Sorry !

**Comment by maximginette** [comment]
Thanks!

**Comment by eureka2** [comment]
@maxypayne
Maybe your problem comes from this [issue](https://github.com/eureka2/G6K/commit/0f76267f419e717ef553d54944b9d58921564864). it's fixed and will be released this weekend.

Best regards!
