### ISSUE TITLE
Installation du simulateur de carte grise

### ISSUE THREAD

**Issue by AlexandreCrisa** [eureka2/G6K#26]
Bonjour à vous,

Je suis en train d'essayer d'installer le simulateur de cartes grises du gouvernement. J'ai pu installé la source de données (fichier json + schéma). Je souhaite désormais importer le simulateur (format xml) et je reçois l'erreur suivante : 
![image](https://user-images.githubusercontent.com/65833035/82766404-4e1e3a00-9e1f-11ea-9adc-92bce81dd511.png)

En vous remerciant pour votre aide

Cordialement,
Alexandre Crisa

**Comment by bageg** [comment]
Bonjour, 

J'ai eu le même problème lors de mon installation. Ce n'est rien de grave, il suffit de supprimer dans le XML les attributs qui sont indiqués dans l'erreur comme interdit. 

6 éléments à la ligne 2 et 6 à la ligne 12. Tout ces attributs étant de toute façon vides. 

Une fois cela fait vous pouvez ré importer le XML et ça passera sans soucis. 

Bonne journée.

**Comment by AlexandreCrisa** [comment]
Bonjour bageg,

Effectivement, ça fonctionne parfaitement après modification.

Je vous remercie pour votre aide !

Bonne journée à vous.

**Comment by rayenhidri27** [comment]
i try to use your application, but when i publish the simulator, i have an xml error
![erreur G6K](https://user-images.githubusercontent.com/50717784/126170978-3e47436b-ed4f-4d3f-a50f-82d069f5941c.png)

im running sf 4.4.25
G6K : 4.48
php 7.4
MySQL 5.7
win 10
local env  : wamp 3.2

also i wanna know what i must do after publishing the simulator to use it (it's not mentioned in the doc, it'll be nice if u add it)
