### ISSUE TITLE
Error just after installation

### ISSUE THREAD

**Issue by rzmendrika** [eureka2/G6K#33]
Symfony\Component\Debug\Exception\FatalThrowableError: Argument 3 passed to FOS\UserBundle\Doctrine\UserManager::__construct() must be an instance of Doctrine\Common\Persistence\ObjectManager, instance of Doctrine\ORM\EntityManager given, called in /media/mendrika/Data/dev/Ilo/G6K/var/cache/dev/ContainerJ0xUTMr/getFosUser_UserManagerService.php on line 13
at FOS.UserBundle.Doctrine.UserManager.__construct(UserManager.php:41)
at require(getFosUser_UserManagerService.php:13)
at ContainerJ0xUTMr.srcApp_KernelDevDebugContainer.load(srcApp_KernelDevDebugContainer.php:481)
at require(getFosUser_UserProvider_UsernameService.php:12)
... 19 more

**Comment by houcemL** [comment]
bonjour

C'est quoi la version de php que vous utilisez ? 
c'est mieux avec les versions php, symfony, doctrine ..

**Comment by rzmendrika** [comment]
Bonjour, 

- Symfony 4.4.12
- PHP 7.3.15-3
![doctrine](https://user-images.githubusercontent.com/64146979/91960128-2ee25300-ed12-11ea-9c7d-c053f23c2a9b.png)

**Comment by eureka2** [comment]
Hello,

It seems that [FOSUserBundle ](https://github.com/FriendsOfSymfony/FOSUserBundle) is no longer compatible with Symfony 4.4

This implies that I have to completely rewrite the user management with the "[Security](https://symfony.com/doc/current/security.html)" component of Symfony and it will take me a while.

Sorry for the inconvenience but if you want to contribute, you are welcome

Best regards

**Comment by rzmendrika** [comment]
Thanks,
So what should I do now? how can I install it for symfony 4.3 for example?

**Comment by eureka2** [comment]
@rzmendrika
I'm actively working on replacing FOSUserBundle, can you wait a week or two?
There is a lot of work, I can't go any faster, sorry!

**Comment by rzmendrika** [comment]
Thanks, It's OK! I cloned another project wich works fine and mine too now.
I don't know if I should open another issue but I want to delete listbox from my project, and I want to ask if there will be an impact elsewhere.

**Comment by houcemL** [comment]
@eureka2  
if it's a fosuser issue may be we should report the bug in theire repos  ... i'm not sure about that i think it's a dependancy issue because i had some similar issue but on another services especially when it come to ManagerRegistry or EntityManager (i was developping some sf command to import data for mysql to be used in by data sources).. or other services of doctrine .. if i found somenthing usefull i will share it with you !

**Comment by DallyRKT** [comment]
@eureka2 
For my part, I saw that right after the installation, I receive a message telling me that the engine is undergoing maintenance. Can you confirm that this is the case or not?

**Comment by rzmendrika** [comment]
@DallyRKT I think we have the same error
Just switch to prod and debug mode to see the right error.
Or check it into your log.

**Comment by houcemL** [comment]
> : Argument 3 passed to FOS\UserBundle\Doctrine\UserManager::__construct() must be an instance of Doctrine\Common\Persistence\ObjectManager, instance of Doctrine\ORM\EntityManager given

try to replace conflict property in you composer.json with this 

"conflict": {
    "symfony/symfony": "*",
    "doctrine/common": ">=3.0",
    "doctrine/persistence": "<1.3"
},

Acually there is some [BC ](https://github.com/doctrine/DoctrineBundle/pull/1202) (breaking changes .. click to see the issue) in doctrine wich causes many bugs even in sf extra bundle caused by deleting some alias ans services ... so it may be this

Good luck

**Comment by eureka2** [comment]
@rzmendrika and @houcemL

You can now install this [release ](https://github.com/eureka2/G6K/releases/tag/4.4.1 )where FOSUserBundle has been replaced by the security component of Symfony.

Please give me a feedback after this installation.

Best regards

**Comment by rzmendrika** [comment]
@eureka2 Thanks,
