### ISSUE TITLE
Installing the users of the administration interface

### ISSUE THREAD

**Issue by DallyRKT** [eureka2/G6K#35]
Hello,

Symfony Version : 4.4.13

Can you please help me? During the installation, I had this error:

> App\G6K\Composer\ScriptHandler::installUsers
Installing the users of the administration interface
Can't execute install users script : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(255) NOT NU' at line 1
Can't set sequence for table user : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'g6k.user' doesn't exist

Merci.

**Comment by eureka2** [comment]
Sorry, I will fix this in the next version.

Pending the correction:
1) Find the 'g6k_user.sql' file in the 'var/data/databases' directory
2) Replace the word 'AUTOINCREMENT' by 'AUTO_INCREMENT'
3) Replace the word 'CLOB' by 'TEXT'
4) Save the file
5) Drop the 'doctrine_migration_versions' table using your database administration tool
6) Drop the 'demo' database using your database administration tool
7) run `php ../composer.phar run-script g6k-scripts`

**Comment by DallyRKT** [comment]
@eureka2 Thank you very much.

**Comment by DallyRKT** [comment]
Hi @eureka2 

Can you please tell me what are the passwords for the first use of the application? For "admin" and for "guest"?

Thank you.

**Comment by eureka2** [comment]
admin1 for the user admin
guest1 for the user guest

**Comment by DallyRKT** [comment]
Thank you very much !

**Comment by fboujnah** [comment]
Hi admin1 for the user admin doesn't work

**Comment by otrikafo** [comment]
> Hi admin1 for the user admin doesn't work

Same here

**Comment by nava-arki** [comment]
The same. I am getting "Invalid credentials" message
