### ISSUE TITLE
Is there a process for updating a simulator/data source?

### ISSUE THREAD

**Issue by Dexter0015** [eureka2/G6K#39]
Hi,

I have a simulator running (https://www.data.gouv.fr/fr/datasets/simulateur-de-cout-du-certificat-dimmatriculation-carte-grise/) which recieve regular updates.

I saw that I can manually edit it and it's data source through the admin panel, but I would like to know if there is a process in place (maybe I didn't found it?) to upgrade a simulator and/or it's data source?

Or Should I delete, than recreate it?

**Comment by eureka2** [comment]
Hi,
No, there is no incremental update of the data source! You must delete it and then re-import it.
It is the same for the xml file of the simulator

**Comment by Dexter0015** [comment]
Hi,
Ok, thats what I tought but just wanted to be sure.

Thanks.

**Comment by rayenhidri27** [comment]
i try to use your application, but when i publish the simulator, i have an xml error
![erreur G6K](https://user-images.githubusercontent.com/50717784/126170978-3e47436b-ed4f-4d3f-a50f-82d069f5941c.png)

im running sf 4.4.25
php 7.4
MySQL 5.7
local env  : wamp 3.2

also i wanna know what i must do after publishing the simulator to use it (it's not mentioned in the doc, it'll be nice if u add it)
