### ISSUE TITLE
GET http://simulateur.tdl/calcul/admin not found

### ISSUE THREAD

**Issue by kiady66** [eureka2/G6K#42]
Hello! Thank you very for creating this application, it helps me a lot.
I'm just having a little problem.

I can run the program, login, and see the presentation of the demo simulation. But when I click on dashboard, there is nothing.

And in the console, it's written : GET http://simulateur.tdl/calcul/admin not found.

Can you help me please?

Thank you very much

**Comment by Kat-99** [comment]
Hello @kiady66, I see that you managed to resolve this. I have the same problem as you and I can't find a solution. Can you tell me how you resolved it?
