### ISSUE TITLE
How to use simulator as API

### ISSUE THREAD

**Issue by ArfaouiHamouda** [eureka2/G6K#5]
Hi , i want to use the simulator as API to be implemented in an externel website , i have added the following lines to the  "EUREKA\G6KBundle\Resources\ config\parameters.yml" file .
```
     api:
         mysimulator:
             step: 2
             action: calculate
```
my simulator works fine , as i have understood from the reading the code and the previous issue the api should run on :
`/calcul/mysimulator/api`
but cause of luck of Symfony knowledge i didn't know how to pass the arguments and as POST or GET Request , Thanks

**Comment by ArfaouiHamouda** [comment]
i have understood the Demo Example and that API Works Good , actually i have imported some Data from
an [External API](https://www.data.gouv.fr/fr/datasets/simulateur-de-cout-du-certificat-dimmatriculation-carte-grise/) to i Which contain different types of Calculation , i Only need 4 Types of Calculations , but i can't figure out What Step to use , or even what steps refer to . Could you help me to implement this API and Understand more the Functionality of your Code .

**Comment by eureka2** [comment]
Hi,

You must locate the step that contains the button that triggers the display of the results.
In your case it's the step 0 and the "calculer" button

The arguments to provide to the API request are the data name / value  pairs that are requested from the user (usage = "input") at this step and the previous steps.

NOTE: I do not provide help for simulators developed by third parties.

**Comment by opportus** [comment]
Hello Jacques,

Here is the query I send to my simulator [`cout-certificat-immatriculation`](https://gitlab.com/pidila/sp-simulateurs-data/blob/master/definitions-des-simulateurs/cout-certificat-immatriculation.xml):

`http://example.com/simulator/calcul/cout-certificat-immatriculation/api?dateMiseEnCirculation=12%2F12%2F2016&declareVehiculeDeCollection=0&declareVehiculeDemonstration=0&demarche=2&departement=30&energie=1&franceOuImport=1&invalidite=0&modificationEnergiePropre=0&puissanceAdministrative=7&quatriemeChangementDomicile=0&receptionCommunautaire=1&tauxCO2=1&transportMarchandises=0&typeImmatriculation=1&typeVehicule=1`

I send that request with curl:

```php
$input = array(
    'demarche' => 2,
    'franceOuImport' => 1,
    'quatriemeChangementDomicile' => 0,
    'modificationEnergiePropre' => 0,
    'typeVehicule' => 1,
    'dateMiseEnCirculation' => '12/12/2016',
    'invalidite' => 0,
    'typeImmatriculation' => 1,
    'receptionCommunautaire' => 1,
    'declareVehiculeDeCollection' => 0,
    'declareVehiculeDemonstration' => 0,
    'puissanceAdministrative' => 7,
    'energie' => 1,
    'tauxCO2' => 1,
    'transportMarchandises' => 0,
    'departement' => 30,
);

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'http://example.com/simulator/calcul/cout-certificat-immatriculation/api?'.http_build_query($input));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

var_dump(curl_exec($ch));
```

Here is the answer I get:

```json
{
    "links":{
        "self":"http:\/\/example.com\/simulator\/calcul\/cout-certificat-immatriculation\/api?dateMiseEnCirculation=12%2F12%2F2016&declareVehiculeDeCollection=0&declareVehiculeDemonstration=0&demarche=2&departement=30&energie=1&franceOuImport=1&invalidite=0&modificationEnergiePropre=0&puissanceAdministrative=7&quatriemeChangementDomicile=0&receptionCommunautaire=1&tauxCO2=1&transportMarchandises=0&typeImmatriculation=1&typeVehicule=1"
    },
    "errors":[],
    "data":{
        "type":"cout-certificat-immatriculation","id":"eJxlUD1PAzEM%2FTXcfHdIMGVA1yJ1qMrU3UrcnqXYCY5T0X9PchUwsFiWn9%2BHXgDDIxXcy0LqawSjJG6an%2Bb3bczj9DIE9BEUz7hSe8EdLilG9Nvr%2BB%2FlJMUUfmEG9Su6ua0Z1JBRzD2PAwrqldBNw0VBPJ7qgXNSaweSG0QKZNgUOAW6kN8E9w%2FOh6asHcuVSunkt8Ak9PC9oXsdPiuYUjNbVpDrZrpLTJ5i5yl6zF1wScxVoBqQ9igG9Ws5zX1roUrPc%2Bz5QUKrqTSq3TMemLv6X2Hb9acCN30D6Yx%2B7A%3D%3D",
        "attributes":{
 "demarche":"2","typeVehicule":"1","dateMiseEnCirculation":"12\/12\/2016","puissanceAdministrative":"7","energie":"1","receptionCommunautaire":"1","tauxCO2":"1","departement":"30"
        },
        "meta":{
            "demarche":"D\u00e9marche","typeVehicule":"Type de v\u00e9hicule","dateMiseEnCirculation":"Date de mise en circulation","puissanceAdministrative":"Puissance administrative","energie":"Energie","receptionCommunautaire":"R\u00e9ception communautaire","tauxCO2":"Taux CO2","departement":"D\u00e9partement"
        }
    }
}
```

My question is why don't I get results such as `taxeY*`?

Here is my config:

```yaml
api:
    cout-certificat-immatriculation:
        step: 0
        action: calculer
```

Regards

**Comment by sdjeffal** [comment]
Hi,

I don't found the file EUREKA\G6KBundle\Resources\ config\parameters.yml for use simulator as API webservice, still exists ? can you help me please. thank you ;)

**Comment by eureka2** [comment]
Hi,

Which version did you install?

**Comment by sdjeffal** [comment]
I install the symfony 4.2

**Comment by sdjeffal** [comment]
For me, the routes API are already declared in file {project_dir}/{simulator}/config/routes/g6k.yaml but don't work. 

When I make a request api, i have this response : 
```
"errors": [
        {
            "status": "422",
            "title": "Unprocessable entity",
            "detail": "API for this simulator is not implemented",
            "source": {
                "pointer": "/data/"
            }
        }
    ]
```

**Comment by sdjeffal** [comment]
it works, Thank you very much for your help

**Comment by sdjeffal** [comment]
the request api don't work with the mode 'prod'. Why ?

**Comment by sdjeffal** [comment]
I found a solution but i don't know if it is good. i copy the file {project_dir}/{simulator}/config/packages/dev/routing.yaml in {project_dir}/{simulator}/config/packages/prod/

I have a other question, is it normal for the response time to be 5000ms ?

**Comment by eureka2** [comment]
You do not have to copy the file `{project_dir}/{simulator}/config/packages/dev/routing.yaml
`

When you switch from dev to prod, you **must** clear all files in `the {project_dir}/{simulator}/var/ `directory

I just did it and the API is working properly.

The response time is 5000ms for the first request because symfony  must (re)generate the cache. It is 400ms for the following queries.

I am using version 4.2.16 of G6K and php 7.1.3! And you ?

**Comment by sdjeffal** [comment]
I used version master-dev of g6k with PHP 7.2.10.
I installed the version 4.2.16 when you switch from dev to prod, API is working.
But At each request the response time is 5000ms as if the cache system is not working

**Comment by eureka2** [comment]
I don't have such a response time, so I don't know how to help you, sorry!

**Comment by kiady66** [comment]
> it works, Thank you very much for your help

@sdjeffal did you just put
![Capture d’écran de 2021-02-23 11-30-35](https://user-images.githubusercontent.com/42970820/108831584-9fd03c80-75ca-11eb-8c3d-50033dcf0682.png)

in        {project_dir}/{simulator}/config/packages/g6k.yaml        and it's worked? Or you did something else?

cause mine always says : 

"API for this simulator is not implemented"

**Comment by rayenhidri27** [comment]
i try to use your application, but when i publish the simulator, i have an xml error
![erreur G6K](https://user-images.githubusercontent.com/50717784/126170978-3e47436b-ed4f-4d3f-a50f-82d069f5941c.png)

im running sf 4.4.25
php 7.4
local env  : wamp 3.2

also i wanna know what i must do after publishing the simulator to use it (it's not mentioned in the doc, it'll be nice if u add it)

**Comment by kiady66** [comment]
@rayenhidri27 you are not in the right issue but in your case just take the xml that they put in their repo and follow the errors

**Comment by rayenhidri27** [comment]
thx for your answer, i just want to know :
1- when i open the xml file, which lines can i modifiy and why im having this error
2- even if i correct the errors, how can i use the simulator ( specially as an API )?

it's not clear in the doc how to use it after that

**Comment by kiady66** [comment]
I don't know in your case, but in my case when i imported the xml, some attributes was not allowed so i just remove them. and it works.
To use it as an API, I just followed what they said above

**Comment by rayenhidri27** [comment]
do u have a discord account ?
or any mean of communication, so we can talk there
in the errors, they mention that there is errors in tags, not just some attributes

**Comment by eureka2** [comment]
Hi,

@rayenhidri27 You cannot publish a simulator if it contains errors or if it is not completely finalized.
In your case, you have to go to the administration panel, open the simulator and add the missing elements, namely fieldsets in panels, chapters and sections in information blocks and fields in fieldsets.
Once you have done this, the button "Try it" (or "tester" in French) appears in the toolbar.
The url to use in production is the one displayed in your browser's address bar during testing without the word "tryIt".

**Comment by kiady66** [comment]
Hi @eureka2,
I implemented your simulator in the company that I am working for. when we make one request, it creates infinite of php-fpm thread. the ticket has not been solved for months, there is an infinite loop. the infinite request is GET /404.html. How do you think i can solve this
![fe](https://user-images.githubusercontent.com/42970820/126315831-09930cc4-25cd-4676-b3c3-ec064aca4200.png)

**Comment by rayenhidri27** [comment]
i'm trying to fill the data, even the optional ones
when i arrive to data step (donnees), i fill all needed information, and then when i save, i get this error as u see below
![erreur-donnees](https://user-images.githubusercontent.com/50717784/126331550-9ccfe321-72c1-4032-bf7c-0a985c328689.png)



would make short video for demo and put it on the readme file ?

it will be so helpfull for every one using this project

**Comment by eureka2** [comment]
it looks like your simulator xml file is inconsistent, did you manually edit it at some point?

Go to `C:\Users\rayen\Desktop\projets\sim2\simulator` and run `php bin/console g6k:simulator:validate -w sim4` and `php bin/console g6k:simulator:validate sim4`

**Comment by rayenhidri27** [comment]
no, i didn't change it manually
it's bloqued when i add data to simulator

do u have a discord account ?
or any mean of communication, so we can talk there

would u make a short video for demo and put it on the readme file ?
it will be so helpfull for every one using this project
