### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by fxw** [eureka2/G6K#8]
Hello

After doing the 2 php command, how can i run thé server ?

The command php app/console server:run deosn’t work

No documentation are mentionnied.

Any support ?

Thanks

**Comment by eureka2** [comment]
Hi, 

There is no server to launch, G6k is a classic PHP application, just use your browser:
http://yourserver/simulator/calcul/demo

or

http://yourserver/simulator/calcul/admin
account: admin/admin1

**Comment by fxw** [comment]
Hello 

Thanks for your support ! It's working now with those url ;) 

Just a quick question, do you have an Rest API or XML webservice plug to G6K to do a simulation to put the frontend outside of g6k ? 

Nice job for your platform by the way.

**Comment by eureka2** [comment]
Hi,
There is an API system but it is neither REST nor XML

See the discussion: [How to use simulator as API](https://github.com/eureka2/G6K/issues/5)

Best regards

**Comment by kiady66** [comment]
Hi, Thank you very much for creating this php application.
I installed it on my local machine and it work very well.
But when i look at your guides, i see that there is a well done front end for administration.

So i go to the login page and i don't the login and password. I can't add a user cause i don't have access to the db file.
when i look at the db file see that there is 2 created default user. but the password is hashed so can you help me please.

thank you very much
