### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by Nulije** [eureka2/G6K#9]
Hi,

I install G6K apparently without errors, demo works fine, but when i try to import some data sources (sur les droits de successions) i've got this error :
![g6k erreur-min](https://user-images.githubusercontent.com/43369721/45681339-8d21c580-bb3d-11e8-869c-f817c9c04549.jpg)

Not really an expert so don't really know what to do :)

Thx for the help

**Comment by eureka2** [comment]
Hi,

this issue is fixed in version 3.3.3

Please, drop all databases and tables created by the previous installation and install the new version 3.3.3

**Comment by Nulije** [comment]
Hi,

Thx a lot, erverything works fine now with the demo.

If i understand correctly i've now to deploy so i can put the simulator on a website. I've modified the files parameters.yml like said in example : 
deployment:
        localhost: cp -f {local.rootdir}/{local.file} /var/www/html/simulator/{remote.dir}/

But when i click on the button deploy, i've this error :
Error returned by the command: 'cp' n'est pas reconnu en tant que commande interne ou externe

Thx in advance for the help

**Comment by eureka2** [comment]
Hi,

it is not the same problem, please open a new issue because I want to close this one concerning the import.

For the reader, it is better to have only one problem per issue, sorry !

**Comment by Nulije** [comment]
ok
